app_id: "c5747edc-3e56-4fa6-939b-43188a1d39fa"
app_secret: "RUqPHMEIJmr]0LPikyIgII=By/al9=77"
redirect: "http://localhost:8000/placement-portal/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/850aa78d-94e1-4bc6-9cf3-8c11b530701c"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
